pub enum Instruction {
    ADD(AritmeticTarget),
    ADC(AritmeticTarget),
    SUB(AritmeticTarget),
    SBC(AritmeticTarget),
    AND(AritmeticTarget),
    OR(AritmeticTarget),
    XOR(AritmeticTarget),
    CP(AritmeticTarget),
    INC(AritmeticTarget),
    DEC(AritmeticTarget),
    CCF(AritmeticTarget),
    SCF(AritmeticTarget),
    RRA(),
    RLA(),
    RRCA(),
    RRLA(),
    CPL(),
    BIT(AritmeticTarget),
    RESET(AritmeticTarget),
    SET(AritmeticTarget),
    SRL(AritmeticTarget),
    RR(AritmeticTarget),
    RL(AritmeticTarget),
    RRC(AritmeticTarget),
    RLC(AritmeticTarget),
    SRA(AritmeticTarget),
    SLA(AritmeticTarget),
    SWAP(AritmeticTarget),
}

#[derive(Copy, Clone)]
pub enum AritmeticTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
}
